default_install_hook_types:
  - commit-msg
  - pre-commit
  - pre-push

repos:
  - repo: https://github.com/bridgecrewio/checkov
    rev: main
    hooks:
      - id: checkov
        stages:
          - pre-push
