name: Checkov Terraform Scan

on:
  push:
    branches: [main]
  pull_request:

jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Checkov (soft fail, skip .github)
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          soft_fail: true
          skip_path: .github
